name: osaa-mvp
services:
  pipeline:
    build: .
    container_name: osaa-mvp-main
    env_file: .env
    volumes:
      - ./datalake:/app/datalake
      - ./sqlMesh:/app/sqlMesh
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - TARGET=${TARGET}
      - USER=${USER}
      - DB_PATH=/app/sqlMesh/osaa_mvp.db
    command: etl